using System.IO;
using System.Text.Json.Nodes;
using System.Windows;
using System.Windows.Controls;
namespace PermanenciaWpf;
public static class Admin {
 public static void Catalogs(MainWindow m){m.Db!.Actor(m.User!);var root=new DockPanel{Margin=new Thickness(28)};var top=new StackPanel();top.Children.Add(UI.Text("Cadastros e usuários",28,true));var kind=UI.Combo(top,"Cadastro",new[]{"Policiais","Viaturas","Serviços","Naturezas de crimes","Usuários do sistema"});string SelectedKind()=>UI.Value(kind)=="Usuários do sistema"?"Usuários":UI.Value(kind);var grid=UI.Grid(("Identificação","label"),("Informações","info"),("Situação","state"));List<JsonObject> records=[];Button? add=null,inactivate=null,remove=null;
  void Refresh(){string k=SelectedKind();records=k=="Usuários"?m.Db.Users(m.User!):m.Db.Catalog(k,true);grid.ItemsSource=UI.Table(records.Select(d=>new JsonObject{["id"]=d.I("id"),["label"]=k=="Policiais"?Rules.Label(d):d.S("name"),["info"]=k switch{"Policiais"=>d.S("rgpm")+" • "+d.S("unit"),"Viaturas"=>d.S("plate")+" • "+d.S("model")+" • "+d.S("unit"),"Serviços"=>d.S("category"),"Usuários"=>d.S("login")+" • "+d.S("role"),_=>""},["state"]=d.B("active")?"Ativo":"Inativo"}));if(add!=null)add.Visibility=k=="Usuários"&&m.User!.S("role")!="Administrador"?Visibility.Collapsed:Visibility.Visible;if(inactivate!=null)inactivate.Visibility=k=="Policiais"?Visibility.Visible:Visibility.Collapsed;if(remove!=null)remove.Visibility=Visibility.Visible;}
  var a=UI.Actions(top);add=UI.Button("+ Novo",()=>{Edit(m,SelectedKind(),null);Refresh();},true);a.Children.Add(add);a.Children.Add(UI.Button("Editar",()=>{Edit(m,SelectedKind(),records.First(d=>d.I("id")==UI.SelectedId(grid)));Refresh();}));inactivate=UI.Button("Inativar",()=>{var d=records.First(d=>d.I("id")==UI.SelectedId(grid));if(!d.B("active"))throw new Exception("Este policial já está inativo.");if(!UI.Confirm("Inativar este policial? Ele deixará de aparecer nas seleções, mas seu histórico será preservado."))return;d["active"]=false;m.Db.SaveCatalog(m.User!,"Policiais",d);Refresh();});a.Children.Add(inactivate);remove=UI.Button("Excluir",()=>{var d=records.First(d=>d.I("id")==UI.SelectedId(grid));if(!UI.Confirm("Excluir este cadastro? O histórico será preservado."))return;if(SelectedKind()=="Usuários")m.Db.DeleteUser(m.User!,d);else m.Db.DeleteCatalog(m.User!,SelectedKind(),d);Refresh();});a.Children.Add(remove);kind.SelectionChanged+=(_,_)=>UI.Try(Refresh);DockPanel.SetDock(top,Dock.Top);root.Children.Add(top);root.Children.Add(grid);m.Page(root);Refresh();
 }
 static void Edit(MainWindow m,string kind,JsonObject? old){var d=old?.Copy()??new JsonObject{["active"]=true};var label=kind=="Usuários"?"Usuários do sistema":kind;var w=UI.Dialog(m,"Cadastro • "+label,650,700);var p=UI.Stack();p.Children.Add(UI.Text(label,25,true));List<Action> save=[];void Input(string key,string fieldLabel){var t=UI.Input(p,fieldLabel,d.S(key));save.Add(()=>d[key]=t.Text.Trim());}void Combo(string key,string fieldLabel,IEnumerable<string> vals){var c=UI.Combo(p,fieldLabel,vals,d.S(key));save.Add(()=>d[key]=UI.Value(c));}
  switch(kind){case "Policiais":Combo("rank","Posto / graduação",Rules.Ranks);Input("qra","QRA");Input("rgpm","RGPM");Combo("unit","Quartel",Rules.Units.Keys);break;case "Viaturas":Input("name","Identificação");Input("plate","Placa");Input("model","Modelo");Combo("unit","Quartel",Rules.Units.Keys);break;case "Serviços":Input("name","Nome");Combo("category","Categoria",new[]{"Ordinário","Serviço em Diária","Serviço extraordinário"});break;case "Naturezas de crimes":Input("name","Natureza");break;case "Usuários":Input("name","Nome");Input("login","Login");Combo("role","Perfil",new[]{"Operador","Administrador"});p.Children.Add(UI.Text(old==null?"Senha inicial":"Nova senha (deixe vazia para manter)"));var password=new PasswordBox();p.Children.Add(password);save.Add(()=>d["password"]=password.Password);break;}
  var active=new CheckBox{Content=kind=="Viaturas"?"Operacional / disponível":"Ativo",IsChecked=d.B("active"),Margin=new Thickness(0,12,0,16)};p.Children.Add(active);p.Children.Add(UI.Button("Salvar cadastro",()=>{foreach(var action in save)action();d["active"]=active.IsChecked==true;if(kind=="Usuários")m.Db!.SaveUser(m.User!,d);else m.Db!.SaveCatalog(m.User!,kind,d);w.DialogResult=true;},true));w.Content=new ScrollViewer{Content=p};w.ShowDialog();
 }
 public static void Audit(MainWindow m){m.Db!.Actor(m.User!,true);m.Db.Purge();var dock=new DockPanel{Margin=new Thickness(28)};var p=new StackPanel();p.Children.Add(UI.Text("Auditoria • últimos 30 dias",28,true));p.Children.Add(UI.Text("Registros automáticos de alterações. Visualizações, PDFs e cópias do Zap não são registrados."));var from=new DatePicker{SelectedDate=DateTime.Today.AddDays(-30),Width=145};var to=new DatePicker{SelectedDate=DateTime.Today,Width=145};var dates=UI.Actions(p);dates.Children.Add(UI.Text("De "));dates.Children.Add(from);dates.Children.Add(UI.Text(" até "));dates.Children.Add(to);var search=UI.Input(p,"Filtrar por usuário, quartel ou ação");var g=UI.Grid(("Data/hora","at"),("Usuário","user"),("Ação","action"),("Quartel","unit"),("Permanência","report"),("Detalhes","details"));void Refresh(){m.Db.Purge();g.ItemsSource=UI.Table(m.Db.Rows("SELECT * FROM audit ORDER BY at DESC,id DESC").Where(d=>(from.SelectedDate==null||DateTime.Parse(d.S("at"))>=from.SelectedDate)&&(to.SelectedDate==null||DateTime.Parse(d.S("at"))<to.SelectedDate.Value.AddDays(1))&&Rules.Norm(d.S("user")+" "+d.S("unit")+" "+d.S("action")).Contains(Rules.Norm(search.Text))));}var auditActions=UI.Actions(p);auditActions.Children.Add(UI.Button("Consultar",Refresh));auditActions.Children.Add(UI.Button("Exportar PDF • últimos 30 dias",()=>AuditOutput.Export(m,m.Db.Rows("SELECT * FROM audit WHERE at >= $0 ORDER BY at DESC,id DESC",DateTime.Now.AddDays(-30).ToString("yyyy-MM-ddTHH:mm:ss"))),true));DockPanel.SetDock(p,Dock.Top);dock.Children.Add(p);dock.Children.Add(g);m.Page(dock);Refresh();}
 public static void Bank(MainWindow m){m.Db!.Actor(m.User!,true);var db=m.Db;var p=UI.Stack();p.Children.Add(UI.Text("Banco de dados e backups",28,true));var files=Directory.Exists(db.BackupDir)?new DirectoryInfo(db.BackupDir).GetFiles("*.bkp"):[];p.Children.Add(UI.Text("Banco ativo\n"+db.PathName+"\n\nTamanho: "+new FileInfo(db.PathName).Length.ToString("N0")+" bytes\nBackups: "+files.Length+"\nÚltimo backup: "+files.OrderByDescending(f=>f.LastWriteTime).FirstOrDefault()?.LastWriteTime.ToString("dd/MM/yyyy HH:mm")));p.Children.Add(UI.Text("Pasta de backups\n"+db.BackupDir));
  p.Children.Add(UI.Button("Criar backup manual / exportar",()=>{var save=new Microsoft.Win32.SaveFileDialog{Filter="Backup Permanência|*.bkp",FileName="PERMANENCIA_MANUAL_"+DateTime.Now.ToString("dd-MM-yyyy_HH-mm-ss")+".bkp"};if(save.ShowDialog(m)==true){db.Backup(save.FileName,false);MessageBox.Show("Backup validado e salvo.");Bank(m);}},true));
  p.Children.Add(UI.Button("Restaurar backup",()=>{var open=new Microsoft.Win32.OpenFileDialog{Filter="Banco / backup|*.db;*.bkp"};if(open.ShowDialog(m)!=true)return;Database.ValidateFile(open.FileName);if(!UI.Confirm("Restaurar "+open.FileName+"?\nO banco ativo será substituído após backup automático. Será necessário entrar novamente."))return;db.Restore(m.User!,open.FileName);m.Login();}));
  p.Children.Add(UI.Button("Alterar local do banco",()=>{var folder=new Microsoft.Win32.OpenFolderDialog{Title="Selecione a nova pasta dos dados"};if(folder.ShowDialog(m)!=true)return;string target=Path.Combine(folder.FolderName,"Permanencia.db");if(!UI.Confirm("Copiar, validar e ativar o banco em "+target+"?"))return;var next=db.Relocate(m.User!,target);m.Db=next;try{m.SaveConfig();}catch{m.Db=db;next.Dispose();throw;}db.Dispose();Bank(m);}));
  p.Children.Add(UI.Button("Alterar pasta de backups",()=>{var folder=new Microsoft.Win32.OpenFolderDialog{Title="Pasta de backups"};if(folder.ShowDialog(m)!=true)return;string previous=db.BackupDir;try{db.BackupDir=folder.FolderName;db.Backup();m.SaveConfig();db.Log(m.User!,"ALTEROU PASTA DE BACKUP",details:folder.FolderName);}catch{db.BackupDir=previous;throw;}Bank(m);}));p.Children.Add(UI.Text("Cada alteração atualiza o backup automático do dia. São mantidos os backups dos 10 dias mais recentes. Dados e backups ficam separados do aplicativo."));m.Page(new ScrollViewer{Content=p});}
}
