using Microsoft.Data.Sqlite;
using System.IO;
using System.Security.Cryptography;
using System.Text.Json.Nodes;
namespace PermanenciaWpf;
public sealed class Database:IDisposable {
 public string PathName{get;} public string BackupDir{get;set;} public SqliteConnection Conn{get;private set;}
 public Database(string path,bool create=false,string? backup=null){
  PathName=Path.GetFullPath(path);BackupDir=backup??Path.Combine(Path.GetDirectoryName(Path.GetDirectoryName(PathName))!,"Backup");
  if(create){Directory.CreateDirectory(Path.GetDirectoryName(PathName)!);using var file=new FileStream(PathName,FileMode.CreateNew);}
  else if(!File.Exists(PathName))throw new Exception("BANCO DE DADOS NÃO ENCONTRADO. Localize ou restaure o banco; nenhum banco vazio foi criado.");
  Conn=new SqliteConnection(new SqliteConnectionStringBuilder{DataSource=PathName,Mode=SqliteOpenMode.ReadWrite,Pooling=false}.ToString());Conn.Open();Execute("PRAGMA foreign_keys=ON");
  try{if(create)Initialize();NormalizeLegacyCategories();NormalizeCatalogData();EnsureWanessaLopes();EnsureReportCreated();EnsureGeneralReports();Check();Purge();}catch{Conn.Dispose();throw;}
 }
 public void Dispose()=>Conn.Dispose();
 public int Execute(string sql,params object?[] values){using var cmd=Command(sql,values);return cmd.ExecuteNonQuery();}
 public object? Scalar(string sql, params object?[] values){using var cmd=Command(sql,values);return cmd.ExecuteScalar();}
 private SqliteCommand Command(string sql,object?[] vs){var c=Conn.CreateCommand();c.CommandText=sql;for(int i=0;i<vs.Length;i++)c.Parameters.AddWithValue("$"+i,vs[i]??DBNull.Value);return c;}
 public List<JsonObject> Rows(string sql,params object?[] vs){using var cmd=Command(sql,vs);using var r=cmd.ExecuteReader();List<JsonObject> rows=[];while(r.Read()){var o=new JsonObject();for(int i=0;i<r.FieldCount;i++)o[r.GetName(i)]=r.IsDBNull(i)?null:JsonValue.Create(r.GetValue(i));rows.Add(o);}return rows;}
 private void Atomic(Action action){Execute("BEGIN IMMEDIATE");try{action();Execute("COMMIT");}catch{Execute("ROLLBACK");throw;}Backup();}
 public static string Hash(string password,string? salt=null){salt??=Convert.ToHexString(RandomNumberGenerator.GetBytes(16)).ToLowerInvariant();return salt+":"+Convert.ToHexString(Rfc2898DeriveBytes.Pbkdf2(password,Convert.FromHexString(salt),260000,HashAlgorithmName.SHA256,32)).ToLowerInvariant();}
 public JsonObject Authenticate(string login,string password){var u=Rows("SELECT * FROM users WHERE login=$0 COLLATE NOCASE AND active=1",login).FirstOrDefault();if(u==null||!CryptographicOperations.FixedTimeEquals(System.Text.Encoding.UTF8.GetBytes(Hash(password,u.S("password").Split(':')[0])),System.Text.Encoding.UTF8.GetBytes(u.S("password"))))throw new Exception("Usuário ou senha incorretos, ou usuário inativo.");return u;}
 public JsonObject Actor(JsonObject u,bool admin=false){var a=Rows("SELECT * FROM users WHERE id=$0 AND active=1",u.I("id")).FirstOrDefault();if(a==null)throw new Exception("Sessão sem acesso. Entre novamente.");if(admin&&a.S("role")!="Administrador")throw new Exception("Acesso exclusivo do Administrador.");return a;}
 public void Log(JsonObject u,string action,string unit="",string report="",string details=""){Execute("INSERT INTO audit(at,user,action,unit,report,details) VALUES($0,$1,$2,$3,$4,$5)",DateTime.Now.ToString("yyyy-MM-ddTHH:mm:ss"),u.S("login"),action,unit,report,details);Execute("UPDATE users SET used=1 WHERE id=$0",u.I("id"));}
 public void Purge()=>Execute("DELETE FROM audit WHERE at<$0",DateTime.Now.AddDays(-30).ToString("yyyy-MM-ddTHH:mm:ss"));
 private void Initialize(){
  Execute("""
CREATE TABLE meta(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE users(id INTEGER PRIMARY KEY,name TEXT NOT NULL,login TEXT NOT NULL UNIQUE COLLATE NOCASE,password TEXT NOT NULL,role TEXT NOT NULL,active INTEGER NOT NULL,used INTEGER NOT NULL DEFAULT 0);
CREATE TABLE catalog(id INTEGER PRIMARY KEY,kind TEXT NOT NULL,data TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,deleted INTEGER NOT NULL DEFAULT 0);
CREATE TABLE reports(id INTEGER PRIMARY KEY,unit TEXT NOT NULL,day TEXT NOT NULL,status TEXT NOT NULL,data TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1,updated TEXT NOT NULL,created TEXT NOT NULL,UNIQUE(unit,day));
CREATE TABLE general_reports(id INTEGER PRIMARY KEY,day TEXT NOT NULL UNIQUE,data TEXT NOT NULL,created TEXT NOT NULL,updated TEXT NOT NULL);
CREATE TABLE defaults(unit TEXT PRIMARY KEY,operation TEXT NOT NULL);
CREATE TABLE audit(id INTEGER PRIMARY KEY,at TEXT NOT NULL,user TEXT NOT NULL,action TEXT NOT NULL,unit TEXT NOT NULL,report TEXT NOT NULL,details TEXT NOT NULL);
CREATE TRIGGER protect_admin_delete BEFORE DELETE ON users WHEN upper(OLD.login)='ADMIN' BEGIN SELECT RAISE(ABORT,'ADMIN protegido'); END;
CREATE TRIGGER protect_admin_update BEFORE UPDATE ON users WHEN upper(OLD.login)='ADMIN' AND (NEW.login!=OLD.login OR NEW.role!='Administrador' OR NEW.active!=1) BEGIN SELECT RAISE(ABORT,'ADMIN protegido'); END;
""");
  Atomic(()=>{
   Execute("INSERT INTO meta VALUES('schema','1'),('application','Permanencia15BPM')");
   foreach(var (l,p) in new[]{("ADMIN","admin"),("15bpm","15bpm")})Execute("INSERT INTO users(name,login,password,role,active) VALUES($0,$0,$1,'Administrador',1)",l,Hash(p));
   foreach(var p in JsonNode.Parse(File.ReadAllText(System.IO.Path.Combine(AppContext.BaseDirectory,"Assets","police.json")))!.AsArray())Insert("Policiais",p!.AsObject());
   foreach(var (cat,names) in new[]{("Ordinário",Array.Empty<string>()),("Serviço em Diária",new[]{"POSTO FISCAL","INDEA","PATRULHA RURAL","CIRETRAN","FÓRUM"}),("Serviço extraordinário",new[]{"CENTRO SEGURO","PATRULHA MARIA DA PENHA","SINFRA","GAP","OPERAÇÃO EXTRA"})})foreach(var n in names)Insert("Serviços",new(){["name"]=n,["category"]=cat,["exclude_zap"]=n=="FÓRUM"||n=="CIRETRAN"});
   foreach(var n in Rules.Natures)Insert("Naturezas de crimes",new(){["name"]=n,["fixed"]=n=="OUTROS"});
  });
 }
 private void Insert(string kind,JsonObject d)=>Execute("INSERT INTO catalog(kind,data) VALUES($0,$1)",kind,d.ToJsonString());
 public void Check(){try{if(Scalar("PRAGMA integrity_check")?.ToString()!="ok")throw new Exception("Falha na integridade SQLite.");var m=Rows("SELECT * FROM meta");if(!m.Any(x=>x.S("key")=="application"&&x.S("value")=="Permanencia15BPM")||!m.Any(x=>x.S("key")=="schema"&&x.S("value")=="1"))throw new Exception("Metadados do Permanência ausentes.");if(!Rows("SELECT * FROM users WHERE login='ADMIN' COLLATE NOCASE AND active=1 AND role='Administrador'").Any())throw new Exception("Conta ADMIN inválida.");foreach(var t in new[]{"catalog","reports","general_reports","defaults","audit"})Rows("SELECT * FROM "+t+" LIMIT 1");}catch(Exception ex){throw new Exception("Arquivo inválido, incompatível ou danificado. O banco atual foi preservado. Detalhe: "+ex.Message, ex);}}
 public static void ValidateFile(string path){using var c=new SqliteConnection(new SqliteConnectionStringBuilder{DataSource=path,Mode=SqliteOpenMode.ReadOnly,Pooling=false}.ToString());c.Open();using var q=c.CreateCommand();q.CommandText="PRAGMA integrity_check";if(q.ExecuteScalar()?.ToString()!="ok")throw new Exception("Banco danificado.");q.CommandText="SELECT value FROM meta WHERE key='application'";if(q.ExecuteScalar()?.ToString()!="Permanencia15BPM")throw new Exception("Arquivo incompatível.");q.CommandText="SELECT value FROM meta WHERE key='schema'";if(q.ExecuteScalar()?.ToString()!="1")throw new Exception("Versão de banco incompatível.");q.CommandText="SELECT count(*) FROM users WHERE login='ADMIN' COLLATE NOCASE AND active=1 AND role='Administrador'";if(Convert.ToInt32(q.ExecuteScalar())!=1)throw new Exception("Conta ADMIN inválida.");foreach(var t in new[]{"catalog","reports","defaults","audit"}){q.CommandText="SELECT * FROM "+t+" LIMIT 1";using var r=q.ExecuteReader();}}
 public List<JsonObject> Catalog(string kind,bool all=false){var list=Rows("SELECT * FROM catalog WHERE kind=$0 AND deleted=0"+(all?"":" AND active=1"),kind).Select(r=>{var d=JsonNode.Parse(r.S("data"))!.AsObject();d["id"]=r.I("id");d["active"]=r.I("active")==1;return d;}).ToList();return kind=="Policiais"?Rules.Ordered(list).ToList():list.OrderBy(p=>p.B("fixed")).ToList();}
 public void SaveCatalog(JsonObject u,string kind,JsonObject data){Actor(u);var d=data.Copy();int id=d.I("id");string[] required=kind switch{"Policiais"=>["rank","qra","rgpm","unit"],"Viaturas"=>["name","plate","model","unit"],"Serviços"=>["name","category"],_=>["name"]};if(required.Any(k=>string.IsNullOrWhiteSpace(d.S(k))))throw new Exception("Preencha todos os campos do cadastro.");if((kind=="Policiais"||kind=="Viaturas")&&!Rules.Units.ContainsKey(d.S("unit")))throw new Exception("Quartel inválido.");var old=id==0?null:Catalog(kind,true).First(x=>x.I("id")==id);
  if(old?.B("fixed")==true&&(d.S("name")!=old.S("name")||!d.B("active")))throw new Exception("OUTROS é uma opção fixa e ativa.");
  if(kind=="Policiais"&&Catalog(kind,true).Any(p=>p.S("rgpm")==d.S("rgpm")&&p.I("id")!=id))throw new Exception("RGPM já cadastrado.");
  if(old!=null)foreach(var k in new[]{"fixed","exclude_zap","cpu_source"})if(old[k]!=null)d[k]=old[k]!.DeepClone();
  bool active=d.B("active");d.Remove("id");d.Remove("active");Atomic(()=>{if(id==0){Insert(kind,d);Execute("UPDATE catalog SET active=$0 WHERE id=last_insert_rowid()",active?1:0);}else Execute("UPDATE catalog SET data=$0,active=$1 WHERE id=$2",d.ToJsonString(),active?1:0,id);Log(u,id==0?"CADASTROU":"EDITOU CADASTRO",details:kind+": "+(d.S("name")+d.S("qra")));});
 }
 public void DeleteCatalog(JsonObject u,string kind,JsonObject d){Actor(u);if(d.B("fixed"))throw new Exception("OUTROS não pode ser excluído.");Atomic(()=>{Execute("UPDATE catalog SET deleted=1 WHERE id=$0 AND kind=$1",d.I("id"),kind);Log(u,"EXCLUIU CADASTRO",details:kind+": "+d.S("name")+d.S("qra"));});}
 public List<JsonObject> Users(JsonObject u){Actor(u);return Rows("SELECT id,name,login,role,active,used FROM users ORDER BY login");}
 public void SaveUser(JsonObject u,JsonObject d){u=Actor(u);int id=d.I("id");var old=Rows("SELECT * FROM users WHERE id=$0",id).FirstOrDefault();if(old==null&&u.S("role")!="Administrador")throw new Exception("Somente Administrador pode cadastrar usuários do sistema.");if(string.IsNullOrWhiteSpace(d.S("name"))||string.IsNullOrWhiteSpace(d.S("login")))throw new Exception("Nome e login são obrigatórios.");if(d.S("role")!="Administrador"&&d.S("role")!="Operador")throw new Exception("Perfil inválido.");if(old?.S("login").ToUpperInvariant()=="ADMIN"){if(d.S("login")!=old.S("login")||d.S("role")!="Administrador"||!d.B("active")||d.S("password")!="")throw new Exception("O usuário ADMIN não pode ser alterado.");}if(old==null&&d.S("password")=="")throw new Exception("Informe uma senha inicial.");string pwd=d.S("password")==""?old!.S("password"):Hash(d.S("password"));Atomic(()=>{if(old==null)Execute("INSERT INTO users(name,login,password,role,active) VALUES($0,$1,$2,$3,$4)",d.S("name"),d.S("login"),pwd,d.S("role"),d.B("active")?1:0);else Execute("UPDATE users SET name=$0,login=$1,password=$2,role=$3,active=$4 WHERE id=$5",d.S("name"),d.S("login"),pwd,d.S("role"),d.B("active")?1:0,id);Log(u,old==null?"CRIOU USUÁRIO":"EDITOU USUÁRIO",details:d.S("login"));});}
 public void DeleteUser(JsonObject u,JsonObject d){Actor(u);var old=Rows("SELECT * FROM users WHERE id=$0",d.I("id")).First();if(old.I("used")!=0||old.S("login").ToUpperInvariant()=="ADMIN"||old.I("id")==u.I("id"))throw new Exception("Conta protegida ou com ações. Utilize Inativar quando permitido.");Atomic(()=>{Execute("DELETE FROM users WHERE id=$0",old.I("id"));Log(u,"EXCLUIU USUÁRIO",details:old.S("login"));});}
 private void NormalizeLegacyCategories(){foreach(var row in Rows("SELECT id,data FROM catalog WHERE kind='Serviços' AND deleted=0")){var service=JsonNode.Parse(row.S("data"))!.AsObject();if(service.S("category")=="Próprio")service["category"]="Serviço em Diária";else if(service.S("category")=="Extraordinário")service["category"]="Serviço extraordinário";else if(service.S("category")=="Operacional"){Execute("UPDATE catalog SET deleted=1 WHERE id=$0",row.I("id"));continue;}else continue;Execute("UPDATE catalog SET data=$0 WHERE id=$1",service.ToJsonString(),row.I("id"));}}
 private void EnsureReportCreated(){if(Rows("PRAGMA table_info(reports)").Any(x=>x.S("name")=="created"))return;Atomic(()=>{Execute("ALTER TABLE reports ADD COLUMN created TEXT");Execute("UPDATE reports SET created=updated WHERE created IS NULL OR created='' ");});}
 private void EnsureGeneralReports()=>Execute("CREATE TABLE IF NOT EXISTS general_reports(id INTEGER PRIMARY KEY,day TEXT NOT NULL UNIQUE,data TEXT NOT NULL,created TEXT NOT NULL,updated TEXT NOT NULL)");
 private void NormalizeCatalogData(){Execute("UPDATE catalog SET kind='Naturezas de crimes' WHERE kind='Naturezas de TCO'");var names=new Dictionary<string,string>{{"Art. 42 LCP — Perturbação do trabalho ou sossego","Perturbação do Sossego"},{"Art. 129 CP — Lesão corporal","Lesão Corporal"},{"Art. 147 CP — Ameaça","Ameaça"},{"Art. 163 CP — Dano","Dano"},{"Art. 330 CP — Desobediência","Desobediência"}};foreach(var row in Rows("SELECT id,data FROM catalog WHERE kind='Naturezas de crimes' AND deleted=0")){var d=JsonNode.Parse(row.S("data"))!.AsObject();if(names.TryGetValue(d.S("name"),out var name)){d["name"]=name;Execute("UPDATE catalog SET data=$0 WHERE id=$1",d.ToJsonString(),row.I("id"));}}foreach(var n in Rules.Natures)if(!Catalog("Naturezas de crimes",true).Any(x=>x.S("name")==n))Insert("Naturezas de crimes",new(){["name"]=n,["fixed"]=n=="OUTROS"});foreach(var row in Rows("SELECT id,data FROM catalog WHERE kind='Policiais' AND deleted=0")){var d=JsonNode.Parse(row.S("data"))!.AsObject();if(d.S("qra")=="RR DE SOUZA"){d["qra"]="WILSON";Execute("UPDATE catalog SET data=$0 WHERE id=$1",d.ToJsonString(),row.I("id"));}}}
 private void EnsureWanessaLopes(){if(!Catalog("Policiais",true).Any(p=>p.S("rgpm")=="886875"))Insert("Policiais",new(){["rank"]="CB PM",["qra"]="WANESSA LOPES",["rgpm"]="886875",["unit"]="SEDE"});}
 private void SetMeta(string key,string value)=>Execute("INSERT INTO meta(key,value) VALUES($0,$1) ON CONFLICT(key) DO UPDATE SET value=excluded.value",key,value);
 private JsonObject PermanentDaily(string name){var stored=Rows("SELECT value FROM meta WHERE key=$0","daily-template-"+name).FirstOrDefault().S("value");if(stored!=""){var value=JsonNode.Parse(stored)!.AsObject();value["permanent"]=true;return value;}var roster=name=="CIRETRAN"?new[]{("1º SGT PM","RR PARREIRA")}:new[]{("1º SGT PM","DANIEL"),("1º SGT PM","LUIZ HENRIQUE"),("3º SGT PM","FERNANDO"),("CB PM","WILSON")};var police=Catalog("Policiais").Where(p=>roster.Any(x=>p.S("rank")==x.Item1&&p.S("qra")==x.Item2)).Select(p=>(JsonNode)p.Copy()).ToArray();return new JsonObject{{"name",name},{"category","Serviço em Diária"},{"permanent",true},{"police",new JsonArray(police)}};}
 public JsonObject New(string unit){var texts=new JsonObject();foreach(var t in Rules.Texts)texts[t]="SEM ALTERAÇÃO";var counts=new JsonObject();foreach(var t in Rules.Prod.Concat(Rules.ZapCounts))counts[t]=0;var result=new JsonObject{["unit"]=unit,["day"]=DateTime.Today.ToString("yyyy-MM-dd"),["operation"]=Rows("SELECT operation FROM defaults WHERE unit=$0",unit).FirstOrDefault().S("operation"),["permanence"]=null,["cpu"]=null,["received"]=null,["incoming"]=null,["outgoing"]=null,["vtrs"]=new JsonArray(),["services"]=new JsonArray(),["occurrences"]=new JsonArray(),["notifications"]=0,["notification_numbers"]=new JsonArray(),["seized"]=0,["seizure_numbers"]=new JsonArray(),["texts"]=texts,["counts"]=counts};if(unit=="SEDE"){result.A("services").Add(PermanentDaily("CIRETRAN"));result.A("services").Add(PermanentDaily("FÓRUM"));}var today=DateTime.Today;foreach(var previous in Rows("SELECT data FROM reports WHERE unit=$0",unit)){var saved=JsonNode.Parse(previous.S("data"))!.AsObject();foreach(var service in saved.A("services").Objects().Where(s=>s.S("category")=="Serviço em Diária"&&!s.B("permanent")&&!new[]{"CIRETRAN","FÓRUM"}.Contains(s.S("name"))&&DateTime.TryParse(s.S("start_day"),out var start)&&DateTime.TryParse(s.S("end_day"),out var end)&&today>=start.Date&&today<=end.Date)){if(!result.A("services").Objects().Any(x=>x.S("name")==service.S("name")&&x.S("start_day")==service.S("start_day")&&x.S("end_day")==service.S("end_day")))result.A("services").Add(service.DeepClone());}}return result;}
 public JsonObject Get(int id){var r=Rows("SELECT * FROM reports WHERE id=$0",id).FirstOrDefault()??throw new Exception("Relatório diário não encontrado.");if(r.S("status")=="EM PREENCHIMENTO"&&DateTime.TryParse(r.S("created"),out var created)&&DateTime.Now>=created.AddHours(24)){Atomic(()=>Execute("UPDATE reports SET status='FINALIZADO' WHERE id=$0",id));r["status"]="FINALIZADO";}var d=JsonNode.Parse(r.S("data"))!.AsObject();d["id"]=id;d["status"]=r.S("status");d["revision"]=r.I("revision");d["created"]=r.S("created");return d;}
 public List<JsonObject> Reports(string? unit=null)=>Rows("SELECT id FROM reports"+(unit==null?"":" WHERE unit=$0")+" ORDER BY day DESC,id DESC",unit==null?[]:[unit]).Select(r=>Get(r.I("id"))).ToList();
 private static void ValidateDailyServices(JsonObject data){var duplicate=data.A("services").Objects().Where(s=>s.S("category")=="Serviço em Diária").GroupBy(s=>Rules.Norm(s.S("name"))).FirstOrDefault(group=>group.Count()>1);if(duplicate!=null)throw new Exception("Serviço em Diária duplicado: "+duplicate.First().S("name")+". Mantenha apenas um serviço com essa identificação no Relatório diário.");}
 public JsonObject Save(JsonObject u,JsonObject data){u=Actor(u);var d=data.Copy();int id=d.I("id"),rev=d.I("revision");var old=id==0?null:Get(id);if(!Rules.Units.ContainsKey(d.S("unit"))||!DateTime.TryParseExact(d.S("day"),"yyyy-MM-dd",null,System.Globalization.DateTimeStyles.None,out _))throw new Exception("Data ou quartel inválido.");if(old!=null){if(!Rules.Editable(u,old))throw new Exception("Prazo de edição encerrado. O relatório não pode mais ser alterado.");if(u.S("role")!="Administrador"&&(d.S("unit")!=old.S("unit")||d.S("day")!=old.S("day")))throw new Exception("Data e quartel não podem ser alterados pelo Operador.");if(rev!=old.I("revision"))throw new Exception("Registro alterado em outra janela. Reabra antes de salvar.");}ValidateDailyServices(d);const string status="EM PREENCHIMENTO";d.Remove("id");d.Remove("revision");d.Remove("status");d.Remove("created");try{Atomic(()=>{var saved=DateTime.Now.ToString("s");if(id==0){Execute("INSERT INTO reports(unit,day,status,data,updated,created) VALUES($0,$1,$2,$3,$4,$4)",d.S("unit"),d.S("day"),status,d.ToJsonString(),saved);id=Rows("SELECT last_insert_rowid() AS id")[0].I("id");}else if(Execute("UPDATE reports SET unit=$0,day=$1,status=$2,data=$3,updated=$4,revision=revision+1 WHERE id=$5 AND revision=$6",d.S("unit"),d.S("day"),status,d.ToJsonString(),DateTime.Now.ToString("s"),id,rev)!=1)throw new Exception("Registro alterado. Reabra antes de salvar.");Execute("INSERT INTO defaults VALUES($0,$1) ON CONFLICT(unit) DO UPDATE SET operation=excluded.operation",d.S("unit"),d.S("operation"));if(d.S("unit")=="SEDE")foreach(var service in d.A("services").Objects().Where(s=>s.S("category")=="Serviço em Diária"&&s.B("permanent")))SetMeta("daily-template-"+service.S("name"),service.ToJsonString());Log(u,old==null?"CRIOU":"EDITOU",d.S("unit"),d.S("day"),$"Relatório diário {id}");});}catch(SqliteException e)when(e.SqliteErrorCode==19){throw new Exception("Já existe um Relatório diário para este quartel e data. Abra o existente no histórico.");}return Get(id);}
 public void DeleteReport(JsonObject u,JsonObject d){u=Actor(u);var report=Get(d.I("id"));if(u.S("role")!="Administrador"&&!Rules.Editable(u,report))throw new Exception("Prazo de edição encerrado. Somente o Administrador pode excluir este relatório.");Atomic(()=>{Execute("DELETE FROM reports WHERE id=$0",d.I("id"));Log(u,"EXCLUIU",report.S("unit"),report.S("day"));});}
 public void SaveGeneral(JsonObject u,GeneralReportResult report){u=Actor(u);Atomic(()=>{string now=DateTime.Now.ToString("s");Execute("DELETE FROM general_reports");Execute("INSERT INTO general_reports(day,data,created,updated) VALUES($0,$1,$2,$2)",report.Day.ToString("yyyy-MM-dd"),report.ToJson().ToJsonString(),now);Log(u,"CONSOLIDOU RELATÓRIO WHATSAPP","GERAL",report.Day.ToString("yyyy-MM-dd"),"Cinco quartéis");});}
 public string? LastGeneral(){var row=Rows("SELECT data FROM general_reports ORDER BY updated DESC,id DESC LIMIT 1").FirstOrDefault();return row==null?null:JsonNode.Parse(row.S("data"))!.S("text");}
 public string Backup(string? target=null,bool automatic=true){Directory.CreateDirectory(BackupDir);bool daily=automatic&&target==null;target??=Path.Combine(BackupDir,"PERMANENCIA_AUTO_"+DateTime.Today.ToString("yyyy-MM-dd")+".bkp");string stage=daily?target+"."+Guid.NewGuid().ToString("N")+".tmp":target;if(!daily&&File.Exists(stage))throw new Exception("Destino já existe. Escolha outro nome.");using(var dest=new SqliteConnection(new SqliteConnectionStringBuilder{DataSource=stage,Pooling=false}.ToString())){dest.Open();Conn.BackupDatabase(dest);}ValidateFile(stage);if(daily){File.Move(stage,target,true);foreach(var f in new DirectoryInfo(BackupDir).GetFiles("PERMANENCIA_AUTO_*.bkp").OrderByDescending(f=>f.LastWriteTime).Skip(10))f.Delete();}return target;}
 public static void CopyDatabase(string source,string target){ValidateFile(source);if(File.Exists(target))throw new Exception("Destino já existe.");Directory.CreateDirectory(Path.GetDirectoryName(target)!);using var a=new SqliteConnection(new SqliteConnectionStringBuilder{DataSource=source,Mode=SqliteOpenMode.ReadOnly,Pooling=false}.ToString());using var b=new SqliteConnection(new SqliteConnectionStringBuilder{DataSource=target,Pooling=false}.ToString());a.Open();b.Open();a.BackupDatabase(b);b.Close();ValidateFile(target);}
 public Database Relocate(JsonObject u,string target){Actor(u,true);Backup();CopyDatabase(PathName,target);var next=new Database(target,backup:BackupDir);next.Log(u,"ALTEROU LOCAL DO BANCO",details:PathName+" → "+target);return next;}
 public void Restore(JsonObject u,string source){Actor(u,true);ValidateFile(source);Backup();string stage=PathName+".restore-"+Guid.NewGuid().ToString("N");CopyDatabase(source,stage);using(var st=new Database(stage,backup:BackupDir))st.Log(u,"RESTAUROU BACKUP",details:source);Conn.Close();try{File.Replace(stage,PathName,null);}finally{Conn.Open();}Check();}
}
