using System.Text.Json.Nodes;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Media;
namespace PermanenciaWpf;
public static class ReportOutput {
 public static FlowDocument Build(JsonObject d){
  var doc=new FlowDocument{PageWidth=794,PageHeight=1123,PagePadding=new Thickness(40),ColumnWidth=714,FontFamily=new FontFamily("Arial"),FontSize=12,Foreground=Brushes.Black,Background=Brushes.White};
  Paragraph P(string text,bool bold=false)=>new(new Run(text)){FontWeight=bold?FontWeights.Bold:FontWeights.Normal,Margin=new Thickness(0,3,0,7)};
  var header=new Table{CellSpacing=0,BorderBrush=Brushes.Black,BorderThickness=new Thickness(0.7)};foreach(var width in new[]{210,294,210})header.Columns.Add(new TableColumn{Width=new GridLength(width)});var hg=new TableRowGroup();header.RowGroups.Add(hg);var row=new TableRow();hg.Rows.Add(row);
  row.Cells.Add(new TableCell(P("VISTO\n\n\n________________________\nCOMANDANTE DA UPM")){TextAlignment=TextAlignment.Center,Padding=new Thickness(8),FontSize=10});var middle=new TableCell{TextAlignment=TextAlignment.Center,Padding=new Thickness(8)};var img=UI.Crest(62);middle.Blocks.Add(new BlockUIContainer(img));middle.Blocks.Add(P("ESTADO DE MATO GROSSO\nPOLÍCIA MILITAR\n"+Rules.Units[d.S("unit")],true));row.Cells.Add(middle);row.Cells.Add(new TableCell(P("VISTO EM\n____/____/________\n\n________________________\nCOORDENADOR OPERACIONAL")){TextAlignment=TextAlignment.Center,Padding=new Thickness(8),FontSize=10});doc.Blocks.Add(header);
  if(d.S("status")!="FINALIZADO")doc.Blocks.Add(P("PRÉVIA — EM PREENCHIMENTO",true));int count=0;void Item(string title,string body){var paragraph=P("");paragraph.TextAlignment=TextAlignment.Left;paragraph.Inlines.Add(new Bold(new Run($"{++count}. {title.ToUpperInvariant()}: ")));paragraph.Inlines.Add(new Run(body));doc.Blocks.Add(paragraph);}
  var day=DateTime.Parse(d.S("day"));Item("Serviço do dia",$"{Rules.Date(d.S("day"))} ({day.ToString("dddd",new System.Globalization.CultureInfo("pt-BR")).ToUpperInvariant()}) DAS 08H00 ÀS 08H00 (24 HORAS);");Item("Recebimento do serviço","RECEBI O SERVIÇO DO "+Rules.Label(d["received"])+" COM TODAS AS ORDENS EM VIGOR;");
  Item("Permanência",Rules.Label(d["permanence"])+";");
  foreach(var (vtr,index) in d.A("vtrs").Objects().Select((value,index)=>(value,index))){var vehicle=vtr["vehicle"];var people=Rules.Names(index==0?vtr.A("police").Objects().Where(p=>p.S("rgpm")!=d["cpu"].S("rgpm")):vtr.A("police").Objects());var text=index==0?"CPU: "+Rules.Label(d["cpu"])+(people!=""?", "+people:""):people;Item("Guarnição "+(index+1).ToString("00")+" — "+vehicle.S("plate"),text+";");}
  foreach(var cat in new[]{"Serviço em Diária","Serviço extraordinário"})foreach(var s in d.A("services").Objects().Where(s=>s.S("category")==cat&&s.A("police").Count>0&&(cat!="Serviço em Diária"||d.S("unit")=="SEDE"))){string title=cat=="Serviço em Diária"?(s.B("permanent")?s.S("name"):s.S("name")+" — PERÍODO: "+Rules.Date(s.S("start_day"))+" A "+Rules.Date(s.S("end_day"))):"SERVIÇO EXTRAORDINÁRIO — "+s.S("name")+" "+s.S("start").Replace(":","H")+" ÀS "+s.S("end").Replace(":","H");Item(title,Rules.Names(s.A("police").Objects())+";");}
  foreach(var t in Rules.Texts)Item(t,d["texts"].S(t));Item("Trânsito",$"NOTIFICAÇÕES: {d.S("notifications")} — "+string.Join(", ",d.A("notification_numbers").Select(x=>x?.ToString()))+$"\nVEÍCULOS APREENDIDOS: {d.S("seized")} — AUTOS: "+string.Join(", ",d.A("seizure_numbers").Select(x=>x?.ToString())));Item("Ocorrências","");
  foreach(var type in new[]{"TCO","B.O."}){var rows=new List<string[]>{new[]{type,"DATA/HORA DO FATO","NATUREZA","GUARNIÇÃO"}};rows.AddRange(d.A("occurrences").Objects().Where(o=>o.S("type")==type).Select(o=>new[]{o.S("number"),Rules.Date(o.S("day"))+" "+o.S("time"),Rules.Nature(o),Rules.Names(o.A("police").Objects())}));if(rows.Count==1)rows.Add(["NÃO HOUVE","—","—","—"]);Table(rows);}
  Item("Produtividade","");Table([Rules.Prod.Append("Veículos apreendidos").ToArray(),Rules.Prod.Select(t=>d["counts"].S(t)).Append(d.S("seized")).ToArray()]);Item("Passagem de serviço","PASSO O SERVIÇO PARA "+Rules.Label(d["incoming"])+" COM TODAS AS ORDENS EM VIGOR.");doc.Blocks.Add(P((d.S("unit")=="SEDE"?"ALTO ARAGUAIA":d.S("unit"))+"-MT, "+day.AddDays(1).ToString("dd/MM/yyyy")+"."));Table([["\n\n____________________________\n"+Rules.Label(d["outgoing"])+"\nCPU SAI DE SERVIÇO","\n\n____________________________\n"+Rules.Label(d["incoming"])+"\nCPU ENTRA DE SERVIÇO"]]);return doc;
  void Table(List<string[]> rows){var table=new Table{CellSpacing=0,Margin=new Thickness(0,5,0,10),FontSize=10};foreach(var _ in rows[0])table.Columns.Add(new TableColumn{Width=new GridLength(714.0/rows[0].Length)});var group=new TableRowGroup();table.RowGroups.Add(group);foreach(var values in rows){var tr=new TableRow();foreach(var val in values)tr.Cells.Add(new TableCell(P(val)){BorderBrush=Brushes.Black,BorderThickness=new Thickness(.5),Padding=new Thickness(5),TextAlignment=TextAlignment.Center});group.Rows.Add(tr);}doc.Blocks.Add(table);}
 }
 public static List<Border> Pages(JsonObject d){var document=Build(d);var paginator=((IDocumentPaginatorSource)document).DocumentPaginator;paginator.ComputePageCount();List<Border> pages=[];for(int i=0;i<paginator.PageCount;i++){var page=paginator.GetPage(i);var grid=new Grid{Width=794,Height=1123,Background=Brushes.White};grid.Children.Add(new System.Windows.Shapes.Rectangle{Fill=new VisualBrush(page.Visual){Stretch=Stretch.None,AlignmentX=AlignmentX.Left,AlignmentY=AlignmentY.Top}});grid.Children.Add(new TextBlock{Text=$"Relatório diário • {Rules.Date(d.S("day"))} • Página {i+1} de {paginator.PageCount}",FontSize=10,HorizontalAlignment=HorizontalAlignment.Right,VerticalAlignment=VerticalAlignment.Bottom,Margin=new Thickness(30,0,40,18),Foreground=Brushes.Black});var border=new Border{Child=grid,Width=794,Height=1123,Background=Brushes.White,Margin=new Thickness(0,8,0,12)};border.Measure(new Size(794,1123));border.Arrange(new Rect(0,0,794,1123));border.UpdateLayout();pages.Add(border);}return pages;}
 public static void Show(Window owner,JsonObject d){var w=UI.Dialog(owner,"Prévia do relatório oficial",940,800);var dock=new DockPanel();var bar=new Grid{Margin=new Thickness(16)};bar.ColumnDefinitions.Add(new ColumnDefinition());bar.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});var title=UI.Text("Relatório oficial • "+(d.S("status")=="FINALIZADO"?"Finalizado":"Prévia"),19,true);title.VerticalAlignment=VerticalAlignment.Center;bar.Children.Add(title);var pages=Pages(d);var save=UI.Button("GERAR PDF",()=>{var dialog=new Microsoft.Win32.SaveFileDialog{Filter="PDF|*.pdf",FileName="RELATORIO_DIARIO_"+DateTime.Parse(d.S("day")).ToString("dd-MM-yyyy")+"_"+Rules.Norm(d.S("unit")).Replace(" ","-")+".pdf"};if(dialog.ShowDialog(w)==true){VisualPdfWriter.Save(pages,dialog.FileName);MessageBox.Show(d.S("status")=="FINALIZADO"?"PDF gerado.":"Prévia em PDF gerada.");}},true);save.HorizontalAlignment=HorizontalAlignment.Right;Grid.SetColumn(save,1);bar.Children.Add(save);DockPanel.SetDock(bar,Dock.Top);dock.Children.Add(bar);var stack=new StackPanel{HorizontalAlignment=HorizontalAlignment.Center};foreach(var p in pages)stack.Children.Add(p);dock.Children.Add(new ScrollViewer{Content=stack,HorizontalScrollBarVisibility=ScrollBarVisibility.Auto,VerticalScrollBarVisibility=ScrollBarVisibility.Auto});w.Content=dock;w.ShowDialog();}
}
